# As YAML Configuration File
http:
  routers:
    router-pihole:
      entrypoints:
        - "web"
      service: pihole-service
      rule: "Host(`pihole.home.local`)"

  services:
    pihole-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.46:80"