---
- name: Verify stacks directory exists (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  tags: ["traefik"]
  file:
    path: "/home/{{ansible_user}}/stacks/traefik/"
    state: directory

- name: Copy traefik static with owner and permissions
  when: inventory_hostname == groups['swarm_managers'][0]
  tags: ["traefik"]
  ansible.builtin.copy:
    src: ./static
    dest: /home/{{ansible_user}}/stacks/traefik/
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0644'

- name: Copy traefik static with owner and permissions
  when: inventory_hostname == groups['swarm_managers'][0]
  tags: ["traefik"]
  ansible.builtin.copy:
    src: ./config
    dest: /home/{{ansible_user}}/stacks/traefik/
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0644'

- name: Generate admin password hash
  when: inventory_hostname == groups['swarm_managers'][0]
  shell: echo $(htpasswd -nb {{traefik_admin_user}} {{traefik_admin_password}}) | sed -e s/\\$/\\$\\$/g
  tags: ["traefik"]
  register: traefikpassword

- name: Create docker-compose stack file (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  tags: ["traefik"]
  template:
    src: traefik-stack.j2
    dest: /home/{{ansible_user}}/stacks/traefik-stack.yml
    mode: 0775

- name: Install jsondiff Python library
  when: inventory_hostname == groups['swarm_managers'][0]
  become: true
  become_method: sudo
  tags: ["pip"]
  pip:
    name: jsondiff

- name: Install pyyaml Python library
  when: inventory_hostname == groups['swarm_managers'][0]
  become: true
  become_method: sudo
  tags: ["pip"]
  pip:
    name: pyyaml

- name: create traefik and access log files.
  file:
      path: "{{ item }}"
      state: touch
  with_items:
    - "/var/log/traefik.log"
    - "/var/log/access.log"
  become: true
  tags: ["traefik"]
  become_method: sudo
  ignore_errors: true

- name: Deploy stack from a compose file (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  tags: ["traefik"]
  become: true
  become_method: sudo
  docker_stack:
    state: present
    name: traefik
    compose:
      - /home/{{ansible_user}}/stacks/traefik-stack.yml
