---
- hosts: localhost
  docker_compose_version: 1.25.0
  become: yes
  become_method: sudo
  tasks:
  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add sudoers users to wheel group
    user:
      name=ansible
      groups=wheel
      append=yes
      state=present
      createhome=yes

  - name: Add sudoers users to vagrant group
    user:
      name=ansible
      groups=vagrant
      append=yes
      state=present
      createhome=yes

  - name: Set up authorized keys for the ansible user
    authorized_key: user=ansible key="{{item}}"
    with_file:
      - ./.ssh/id_rsa.pub

  - name: Upgrade all packages to the latest version
    become: true
    become_method: sudo
    tags: ["apt"]
    apt:
      name: "*"
      state: latest
      force_apt_get: true
      update_cache: yes

  - name: Verify system dependencies
    become: true
    become_method: sudo
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-pip
        - python-pip
        - apache2-utils
      state: present
      force_apt_get: true
      update_cache: yes
    tags: ["apt"]

  - name: Install Docker GPG key
    become: true
    become_method: sudo
    shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -"
    tags: ["docker"]

  - name: install docker
    apt:
      name: "{{item}}"
      state: latest
      force_apt_get: true
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Check current docker-compose version.
    command: docker-compose --version
    register: docker_compose_vsn
    changed_when: false
    failed_when: false
    check_mode: no

  - set_fact:
      docker_compose_current_version: "{{ docker_compose_vsn.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"
    when:
      - docker_compose_vsn.stdout is defined

  - name: Install or upgrade docker-compose
    get_url: 
      url : "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
      dest: /usr/local/bin/docker-compose
      mode: 'a+x'
      force: yes
    when: >
      docker_compose_current_version is not defined
      or docker_compose_current_version is version(docker_compose_version, '<')

  - name: Add "{{ansible_user}}" user to "docker" group
    become: true
    become_method: sudo
    shell: "adduser {{ansible_user}} docker"
    tags: ["docker"]
    
 